/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubCategoryRouteImport } from './routes/subCategory'
import { Route as EstablishmenRouteImport } from './routes/establishmen'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CityRouteImport } from './routes/city'
import { Route as CategoryRouteImport } from './routes/category'
import { Route as IndexRouteImport } from './routes/index'

const SubCategoryRoute = SubCategoryRouteImport.update({
  id: '/subCategory',
  path: '/subCategory',
  getParentRoute: () => rootRouteImport,
} as any)
const EstablishmenRoute = EstablishmenRouteImport.update({
  id: '/establishmen',
  path: '/establishmen',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/category': typeof CategoryRoute
  '/city': typeof CityRoute
  '/content': typeof ContentRoute
  '/establishmen': typeof EstablishmenRoute
  '/subCategory': typeof SubCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/category': typeof CategoryRoute
  '/city': typeof CityRoute
  '/content': typeof ContentRoute
  '/establishmen': typeof EstablishmenRoute
  '/subCategory': typeof SubCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/category': typeof CategoryRoute
  '/city': typeof CityRoute
  '/content': typeof ContentRoute
  '/establishmen': typeof EstablishmenRoute
  '/subCategory': typeof SubCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/category'
    | '/city'
    | '/content'
    | '/establishmen'
    | '/subCategory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/category'
    | '/city'
    | '/content'
    | '/establishmen'
    | '/subCategory'
  id:
    | '__root__'
    | '/'
    | '/category'
    | '/city'
    | '/content'
    | '/establishmen'
    | '/subCategory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRoute
  CityRoute: typeof CityRoute
  ContentRoute: typeof ContentRoute
  EstablishmenRoute: typeof EstablishmenRoute
  SubCategoryRoute: typeof SubCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subCategory': {
      id: '/subCategory'
      path: '/subCategory'
      fullPath: '/subCategory'
      preLoaderRoute: typeof SubCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/establishmen': {
      id: '/establishmen'
      path: '/establishmen'
      fullPath: '/establishmen'
      preLoaderRoute: typeof EstablishmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city': {
      id: '/city'
      path: '/city'
      fullPath: '/city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRoute,
  CityRoute: CityRoute,
  ContentRoute: ContentRoute,
  EstablishmenRoute: EstablishmenRoute,
  SubCategoryRoute: SubCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
